on:
  release:
    types: [created]

jobs:
  release:
    name: Release ${{ matrix.TARGET }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - TARGET: x86_64-pc-windows-gnu
            ARCHIVE: zip
          - TARGET: x86_64-unknown-linux-musl
            ARCHIVE: "tar.gz tar.xz tar.zst"
          - TARGET: x86_64-apple-darwin
            ARCHIVE: zip

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.TARGET }}
          ARCHIVE_TYPES: ${{ matrix.ARCHIVE }}

